import type { Provider, ProviderKind } from './types.ts'

export type PresetCategory = 'official' | 'relay' | 'cn' | 'aggregator' | 'local' | 'custom'

export interface ProviderPreset {
  id: string
  name: string
  kind: ProviderKind
  category: PresetCategory
  baseUrl: string
  description: string
  /** Where to create an API key. */
  keyUrl?: string
  docsUrl?: string
  hidden?: boolean
  /** Avatar colours (hex). */
  color: string
  monogram: string
  /** Suggested model ids; the live list from the provider is always preferred. */
  modelHints: string[]
  defaults: Partial<Provider>
}

export const PRESETS: ProviderPreset[] = [
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    kind: 'anthropic',
    category: 'official',
    baseUrl: 'https://api.anthropic.com',
    description: 'Claude 官方 API，支持自适应思考与提示缓存',
    keyUrl: 'https://platform.claude.com/settings/keys',
    color: '#D97757',
    monogram: 'C',
    modelHints: ['claude-opus-5-5', 'claude-sonnet-5-5', 'claude-haiku-4-5', 'claude-fable-5-1'],
    defaults: {
      model: 'claude-opus-5-5',
      thinking: 'adaptive',
      promptCaching: true,
      sendReasoningEffort: true,
      sendSampling: false,
      maxOutputTokens: 64000,
      pricing: { input: 4, output: 20, cachedInput: 0.2 },
    },
  },
  {
    id: 'openai',
    name: 'OpenAI',
    kind: 'openai',
    category: 'official',
    baseUrl: 'https://api.openai.com/v1',
    description: 'OpenAI 官方 API，支持 Responses 与 Chat Completions',
    keyUrl: 'https://platform.openai.com/api-keys',
    color: '#10A37F',
    monogram: 'O',
    modelHints: [],
    defaults: { openaiApi: 'responses', sendReasoningEffort: true, sendSampling: false },
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    kind: 'gemini',
    category: 'official',
    baseUrl: 'https://generativelanguage.googleapis.com',
    description: 'Gemini 原生接口，保留思考签名与多模态',
    keyUrl: 'https://aistudio.google.com/apikey',
    color: '#4285F4',
    monogram: 'G',
    modelHints: [],
    defaults: { sendReasoningEffort: true, sendSampling: true },
  },
  {
    id: 'cpa', name: 'CPA / CLIProxyAPI', kind: 'openai', category: 'relay',
    baseUrl: 'http://127.0.0.1:8317/v1',
    description: '连接已部署的 CPA，按网关配置选择接口与模型',
    docsUrl: 'https://github.com/router-for-me/CLIProxyAPI',
    color: '#2563EB', monogram: 'CP', modelHints: [], defaults: { sendSampling: false },
  },
  {
    id: 'sub2api', name: 'Sub2API', kind: 'anthropic', category: 'relay', baseUrl: 'https://',
    description: '使用网关 Key，接口类型须匹配 Key 所属分组',
    docsUrl: 'https://github.com/Wei-Shaw/sub2api',
    color: '#7C3AED', monogram: 'S2', modelHints: [], defaults: { thinking: 'off', sendSampling: false },
  },
  {
    id: 'grok2api', name: 'Grok2API', kind: 'openai', category: 'relay', baseUrl: 'https://',
    description: '连接 Grok 网关，从实际部署读取可用模型',
    docsUrl: 'https://github.com/chenyme/grok2api',
    color: '#252525', monogram: 'Gk', modelHints: [], defaults: { sendSampling: false },
  },
  {
    id: 'newapi', name: 'New API', kind: 'openai', category: 'relay', baseUrl: 'https://',
    description: '使用站点签发的令牌，按渠道选择兼容接口',
    docsUrl: 'https://github.com/QuantumNous/new-api',
    color: '#0D9488', monogram: 'N', modelHints: [], defaults: { sendSampling: false },
  },
  {
    id: 'relay', name: '通用中转站', kind: 'openai', category: 'relay', baseUrl: 'https://',
    description: '填写中转地址与 Key，再选择站点支持的接口协议',
    color: '#64748B', monogram: '{}', modelHints: [], defaults: { sendSampling: false },
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    kind: 'openai',
    category: 'cn',
    baseUrl: 'https://api.deepseek.com/v1',
    description: '深度求索，性价比高，支持思考内容回传',
    keyUrl: 'https://platform.deepseek.com/api_keys',
    color: '#4D6BFE',
    monogram: 'D',
    modelHints: ['deepseek-chat', 'deepseek-reasoner'],
    defaults: { model: 'deepseek-chat', sendReasoningContent: true, sendSampling: true, maxOutputTokens: 8192 },
  },
  {
    id: 'moonshot',
    name: 'Kimi (Moonshot)',
    kind: 'openai',
    category: 'cn',
    baseUrl: 'https://api.moonshot.cn/v1',
    description: '月之暗面 Kimi 开放平台',
    keyUrl: 'https://platform.moonshot.cn/console/api-keys',
    color: '#1F1F1F',
    monogram: 'K',
    modelHints: [],
    defaults: { sendReasoningContent: true, sendSampling: true },
  },
  {
    id: 'zhipu',
    name: '智谱 GLM',
    kind: 'openai',
    category: 'cn',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    description: '智谱 AI 开放平台（OpenAI 兼容）',
    keyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    color: '#3859FF',
    monogram: '智',
    modelHints: [],
    defaults: { sendReasoningContent: true, sendSampling: true },
  },
  {
    id: 'dashscope',
    name: '阿里云百炼',
    kind: 'openai',
    category: 'cn',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    description: '通义千问等模型（OpenAI 兼容模式）',
    keyUrl: 'https://bailian.console.aliyun.com/?apiKey=1',
    color: '#FF6A00',
    monogram: '百',
    modelHints: [],
    defaults: { sendReasoningContent: true, sendSampling: true },
  },
  {
    id: 'volcengine',
    name: '火山方舟',
    kind: 'openai',
    category: 'cn',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    description: '字节跳动豆包等模型，模型名填推理接入点或模型 ID',
    keyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    color: '#1664FF',
    monogram: '火',
    modelHints: [],
    defaults: { sendReasoningContent: true, sendSampling: true },
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    kind: 'openai',
    category: 'cn',
    baseUrl: 'https://api.minimaxi.com/v1',
    description: 'MiniMax 开放平台（OpenAI 兼容）',
    keyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    color: '#E6334A',
    monogram: 'M',
    modelHints: [],
    defaults: { sendReasoningContent: true, sendSampling: true },
  },
  {
    id: 'siliconflow',
    name: '硅基流动',
    kind: 'openai',
    category: 'aggregator',
    baseUrl: 'https://api.siliconflow.cn/v1',
    description: '国内聚合平台，一个 Key 用多家开源模型',
    keyUrl: 'https://cloud.siliconflow.cn/account/ak',
    color: '#7C3AED',
    monogram: '硅',
    modelHints: [],
    defaults: { sendReasoningContent: true, sendSampling: true },
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    kind: 'openai',
    category: 'aggregator',
    baseUrl: 'https://openrouter.ai/api/v1',
    description: '海外聚合平台，覆盖主流闭源与开源模型',
    keyUrl: 'https://openrouter.ai/keys',
    color: '#6467F2',
    monogram: 'R',
    modelHints: [],
    defaults: { sendReasoningEffort: true, sendSampling: true },
  },
  {
    id: 'ollama',
    name: 'Ollama',
    kind: 'openai',
    category: 'local',
    baseUrl: 'http://127.0.0.1:11434/v1',
    description: '本机运行的开源模型，无需 Key',
    color: '#0F0F0F',
    monogram: 'Ol',
    modelHints: [],
    defaults: { sendSampling: true },
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    kind: 'openai',
    category: 'local',
    baseUrl: 'http://127.0.0.1:1234/v1',
    description: 'LM Studio 本地服务器',
    color: '#4338CA',
    monogram: 'LM',
    modelHints: [],
    defaults: { sendSampling: true },
  },
  {
    id: 'custom-openai',
    hidden: true,
    name: '自定义 · OpenAI 兼容',
    kind: 'openai',
    category: 'custom',
    baseUrl: 'https://',
    description: '任何实现 /chat/completions 的服务或中转',
    color: '#64748B',
    monogram: '{}',
    modelHints: [],
    defaults: { sendSampling: true },
  },
  {
    id: 'custom-anthropic',
    hidden: true,
    name: '自定义 · Anthropic 兼容',
    kind: 'anthropic',
    category: 'custom',
    baseUrl: 'https://',
    description: '实现 /v1/messages 的服务（地址不含 /v1）',
    color: '#64748B',
    monogram: '{}',
    modelHints: [],
    defaults: { thinking: 'off', sendSampling: true },
  },
  {
    id: 'custom-gemini',
    hidden: true,
    name: '自定义 · Gemini 兼容',
    kind: 'gemini',
    category: 'custom',
    baseUrl: 'https://',
    description: '实现 Gemini generateContent 的服务或中转',
    color: '#64748B',
    monogram: '{}',
    modelHints: [],
    defaults: { sendSampling: true },
  },
]

export const CATEGORY_LABELS: Record<PresetCategory, string> = {
  official: '官方',
  relay: '中转与自建',
  cn: '国内厂商',
  aggregator: '聚合平台',
  local: '本地模型',
  custom: '自定义',
}

export function findPreset(id: string | undefined): ProviderPreset | undefined {
  return id ? PRESETS.find((p) => p.id === id) : undefined
}
